### ISSUE TITLE
Drop PHP 5 support

### ISSUE THREAD

**Issue by henriquemoody** [sokil/php-isocodes#13]
Is there a specific reason why you're keeping the support with version 5.5 of PHP since PHP itself does not support that anymore?

Maybe you could _modernize_ the codeback in `master` and still keep the support for old versions in another branch.

**Comment by sokil** [comment]
Idea of dropping PHP 5 support is good. This is last stat about php versions https://seld.be/notes/php-versions-stats-2018-1-edition, and php 5 still used, but I don't think that there are much users of this lib with php < 7 but it's possible.

There is a problem that iso database updated with incrementing lib version, and if I remove support of PHP 5, then users will loose database updates. And supporting of two versions, one of which is almost unusable, is hard.

Is anyone there with PHP < 7? 

I propose to add notification about end of support from 2019-05-01. This will give someone time to update its environment or to add some proposals )

**Comment by henriquemoody** [comment]
Unfortunately there will be always some people using old versions, and that can't be helped. If someone is still using PHP 5.5 they are in trouble with lots of packages -- lots of them. 

As a maintainer of an open source project, as you are, I try to make my life better and keeping compatibility with old versions is more work for me. It may sound selfish, but as you know, keeping an open source project alive is time consuming, so if I make my life easier I'm probably delivering more value as well.

I like the idea of adding the notification and already start working on version 3.0, I would also suggest to drop version < 7.2, since 7.1 is already since it will not have security support in 7 months! I can already start working on making the code fully compatible with PHP >= 7.2.

**Comment by mazentouati** [comment]
It would be great if you elaborate a road-map for the V3, I'd like to help too.

**Comment by henriquemoody** [comment]
Closed by #17
