### ISSUE TITLE
Dynamic translations

### ISSUE THREAD

**Issue by albertovincenzi** [sokil/php-isocodes#24]
Hello,
thanks for this great package.
I was wondering: in our application, we have user language in ISO639 format (en, es, fr, de, it....)
How would be possible to return translations of countries and languages according to this? I saw you allow to set LC_ALL variable and so on but I was wondering which might be the possibilities to avoid that.

Thanks!

**Comment by sokil** [comment]
Hello.

This library uses PHP's native gettext method, which depends of user's locale. 
So language passed through env variables or/and `setlocale` method.
It's a good point to get localised point without modifying user's locale but currently it's not possible.
To implement this feature native gettext feature must be replaces with other gettext pocessor which allows to pass language directly without modifying locale.

btw why you can't change user's locale?

**Comment by albertovincenzi** [comment]
We use the package in Laravel but we manage user locale with laravel standard function which I think doesn't change the locale.

**Comment by sokil** [comment]
Since 3.2 you may implement `Sokil\IsoCodes\TranslationDriver\TranslationDriverInterface` and create yor own translation driver instead of gettext extension. Hope this helps.

See https://github.com/sokil/php-isocodes#translation-drivers for details
