### ISSUE TITLE
Reduce the size of the repository

### ISSUE THREAD

**Issue by henriquemoody** [sokil/php-isocodes#37]
First of all, thank you for all of the work you put into this library, it's very useful and I'm very happy with it.

I recently integrated this library into Respect/Validation:

- https://github.com/Respect/Validation/commit/9c9c76ebfbf8821738accb76a80cabb954cdd99e
- https://github.com/Respect/Validation/commit/f9b9dd21f9e19f55f7c43389bcdd9bb0c1204e38
- https://github.com/Respect/Validation/commit/5450ef86a862c5316c39504ca8afaf9c10ab91a3
- https://github.com/Respect/Validation/commit/2060207f44bde9cae6f42c3d13c777b011b4de01

The problem, however, is that it increased the size of the repository way too much: https://github.com/Respect/Validation/issues/1340

If I look at the directory size in this repository, I get this:

```
$ du -sh *
4.0K	CHANGELOG.md
4.0K	CONTRIBUTING.md
4.0K	LICENSE
12K	README.md
12K	benchmarks
16K	bin
4.0K	composer.json
4.7M	databases
4.0K	infection.json.dist
86M	messages
4.0K	phpbench.json
4.0K	phpcs.xml.dist
4.0K	phpunit.xml.dist
4.0K	psalm.xml
104K	src
44K	tests
```

Clearly, the messages directory is the cause of the issues users are experiencing. The funny is that, for listing the data in English (which is what I use in the validation), none of those translations are useful. 

Would be an idea to have those messages as a third-party repository that could be just a suggestion, so that people can chose whether they want to have all the translations or not?

**Comment by sokil** [comment]
hi
i already thought abouth that, and currently on the way to separate this. there is a feature to update databases separately, and library is for backward compatibility with uses who already require it. so giving choose between composer package with regualary updated database and own update process is good point. 

will made this soon in next major release

**Comment by sokil** [comment]
Implemented in [v.4.0.0](https://github.com/sokil/php-isocodes/releases/tag/4.0.0)

Please, check [installation notes](https://github.com/sokil/php-isocodes#installation)
