### ISSUE TITLE
PHP 8.1.1 - PHP Deprecated Warning: AbstractDatabase::current() ReturnTypeWillChange

### ISSUE THREAD

**Issue by stevenjcarr** [sokil/php-isocodes#53]
$ php composer.phar info | grep iso
sokil/php-isocodes            4.0.1     ISO country, subdivision, language, currency and scri...
sokil/php-isocodes-db-i18n    4.0.1     Database and internationalisation filed for ISO count...

$ php -v
PHP 8.1.1 (cli) (built: Dec 17 2021 23:49:52) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.1, Copyright (c), by Zend Technologies

----

When running one of my scripts I'm getting the deprecation message below when executing the following command:

$country = ((new IsoCodesFactory())->getCountries()->getByAlpha2($countryCode));

PHP Deprecated:  Return type of Sokil\IsoCodes\AbstractDatabase::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ***/vendor/sokil/php-isocodes/src/AbstractDatabase.php on line 182

**Comment by sokil** [comment]
Released in v.4.0.2
