### ISSUE TITLE
Attempted to call function "bindtextdomain" from the global namespace.

### ISSUE THREAD

**Issue by maxlen** [sokil/php-isocodes#59]
Hi.
I've Installed and maintained this package (on Symfony6, php 8.1, docker/ubuntu)
and I got an error "Attempted to call function "bindtextdomain" from the global namespace."

I try it locally from docker container.
`
class IsoCodesService
{
    public function __construct()
    {
        // define locale
        putenv('LANGUAGE=uk_UA.UTF-8');
        putenv('LC_ALL=uk_UA.UTF-8');
        setlocale(LC_ALL, 'uk_UA.UTF-8');
        $this->isoCodes = new IsoCodesFactory(null, new GettextExtensionDriver());
    }

    public function getAlpha3ByAlpha2(string $lang = 'en'): string
    {
        $languages = $this->isoCodes->getLanguages();
        $language = $languages->getByAlpha2($lang);
        return $language->getAlpha3();
    }
}`

Чи не могли б ви допомогти, будьлазка?

**Comment by sokil** [comment]
Привіт. Якщо використовувати драйвер перекладів gettext, треба щоб він був встановлений як екстеншн.

**Comment by maxlen** [comment]
та я б і без нього міг би.
В мене задача така, робити з en -> eng, uk -> ukr i так далі.
Спочатку робив так:
composer remove sokil/php-isocodes
composer remove sokil/php-isocodes-db-i18n

та в коді:

`
$this->isoCodes = new IsoCodesFactory();

$languages = $this->isoCodes->getLanguages();

$language = $languages->getByAlpha2($lang);

return $language->getAlpha3();
`

Якщо ви про то, чи встановлював я ось це, то да:
composer require gettext/gettext


але схоже що тут https://en.wikipedia.org/wiki/ISO_3166-1  немає 'en'.
Чи є у вашому пакеті можливість перекладати з ISO 639-2 to 639-3 ?

Дякую.

**Comment by maxlen** [comment]
якщо можете - будьлазка підкажіть в чому може бути проблема

**Comment by sokil** [comment]
https://github.com/sokil/php-isocodes#dummy-driver

```
<?php

$isoCodes = new IsoCodesFactory(
    null,
    new DummyDriver()
);
```

Якщо не потрібні переклади, просто вимкніть їх ось так

**Comment by sokil** [comment]
якщо вам потрібно просто конвертувати код мови між альфа 2 і 3 то ця бібліотека для вас дуже важка. мови змінюються рідко, просто зробіть мапінг
