### ISSUE TITLE
How can I get the countries with alphabetically order ?

### ISSUE THREAD

**Issue by axmedbek** [sokil/php-isocodes#60]

**Comment by sokil** [comment]
Sort them? 🤔

**Comment by axmedbek** [comment]
Yes , I can sort , but I thought there is an option for this.
And why default sorting with alpha code ?

By the way , who wants to sort , can use : 

`usort($your_country_list, function($a, $b) {
            return strcmp($a->getName(),$b->getName());
});`

**Comment by sokil** [comment]
sorting is not problem of this library, its just a database with localisation.
