### ISSUE TITLE
How can I get the common name in countries ?

### ISSUE THREAD

**Issue by talehorucov** [sokil/php-isocodes#71]
Some country names return incorrectly. For instance: Tanzania, United Republic of | Moldova, Republic of. 
In iso_3166-1.json database return:

> {
      "alpha_2": "MD",
      "alpha_3": "MDA",
      "common_name": "Moldova",
      "flag": "🇲🇩",
      "name": "Moldova, Republic of",
      "numeric": "498",
      "official_name": "Republic of Moldova"
    },

How can I get the common_name ?

**Comment by sokil** [comment]
Check version https://github.com/sokil/php-isocodes/releases/tag/4.2.0
