### ISSUE TITLE
Some country names are incorrect

### ISSUE THREAD

**Issue by talehorucov** [sokil/php-isocodes#75]
Some country names are incorrect, for example "Congo, The Democratic Republic of the". These names end with "Republic of", "Republic of the", "States of", "State of" , so consist of 2 part , seperates with comma.

**Comment by sokil** [comment]
this library is just php binding for https://salsa.debian.org/iso-codes-team/iso-codes/-/blob/main/data/iso_3166-1.json#L353-358, you may ask any questions about content of database and localisation on issues of this repository
