### ISSUE TITLE
Missing or uncommon common names

### ISSUE THREAD

**Issue by hashimaziz1** [sokil/php-isocodes#78]
Hi Sokil, firstly thanks for this library and the great work you've done and continue to do on it.

I was testing the library and noticed that many of the countries have missing common names or their common name is (in English) not commonly used. I'd prefer to make these changes upstream instead of just our own application, so I wanted to ask permission here so I can go ahead and make this commit. The proposed changes that I would make are:

```
Bonaire, Sint Eustatius and Saba = Carribbean Netherlands
British Indian Ocean Territory = the British Indian Ocean Territory
Central African Republic = the Central African Republic
Congo, the Democratic Republic of the = the DRC
Congo = Congo-Brazzaville
Côte d'Ivoire = the Ivory Coast
Falkland Islands (Malvinas) = the Falkland Islands
Faroe Islands = the Faroe Islands
French Southern Territories = the French Southern Territories
Holy See (Vatican City State) = Vatican City
Isle of Man = the Isle of Man
Marshall Islands  = the Marshall Islands
Micronesia, Federated State of = the Federated States of Micronesia
Northern Mariana Islands = the Northern Mariana Islands
Palestine, State of = Palestine
Russian Federation = Russia
Philippines = the Philippines
Pitcairns = the Pitcairn Islands
Saint Martin (French Part) = Saint Martin
Sint Maarten (Dutch Part) = Sint Maarten
Solomon Islands = the Solomon Islands
Turks and Caicos Islands = the Turks and Caicos Islands
United Arab Emirates = the United Arab Emirates
United Kingdom = the United Kingdom
United States = the United States
Virgin Islands, British = the British Virgin Islands
Vrigin Islands, U.S. = the U.S. Virgin Islands
```

Some of these are taken from sources like Wikipedia titles, some from my own knowledge/experience of how these countries would be used by an English speaker, especially in the context of being used in an interface, and some just have the definite article added to nouns like islands because it sounds much more natural in English sentences and avoids having to programmatically check for and add it one at a time.

Let me know what you think.

**Comment by sokil** [comment]
Hi.

Most job is done by Debian community in repo:

https://salsa.debian.org/iso-codes-team/iso-codes#status-of-translations

This library is only the wrapper that use Debian's database abd translations.

Base library (this) even goes without database and translations so you may download it yourself as frequently as you want.

So i cant accept any pull requests to database and translations.

But you may go directly to debuans repo link and make pull requets there.

If it will be accepted, soontgus changes will be in this library too.

**Comment by hashimaziz1** [comment]
Perfect, thank you.
