### ISSUE TITLE
Subdivisions->getAllByCountryCode($code) throws exceptions if no subdivisions are present

### ISSUE THREAD

**Issue by mattyglover** [sokil/php-isocodes#8]
Just wondering if you would consider returning a null set of subdivisions for a country code if no subdivisions exist rather than throwing an internal exception due to the missing country_code key?

`    
public function getAllByCountryCode($code)
    {
        try {
            $subdivisions = $this->find('country_code', $code);
        }
        catch (\Exception $e) {
            // do nothing
            $subdivisions = null;
        }
        return $subdivisions;
    }
`

**Comment by sokil** [comment]
hi.i will research this soon

**Comment by sokil** [comment]
fixed in 2.1
